In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    recall_score
)

from fairlearn.metrics import (
    MetricFrame,
    selection_rate,
    true_positive_rate,
    false_positive_rate,
    demographic_parity_difference,
    equalized_odds_difference
)

print("Libraries loaded successfully")

Libraries loaded successfully


In [6]:

individual = pd.read_csv("ihds_individual_data.tsv", sep="\t")

/var/folders/rt/g1_x8zrs5fd4xd6r10k55jrm0000gn/T/ipykernel_5998/1422051156.py:1: DtypeWarning: Columns (0: SURVEY, 1: PERSONID, 2: IDPERSON, 3: WT, 4: FWT, 5: DIST01, 6: DISTRICT, 7: RO3, 8: RO4, 9: RO5, 10: RO6, 11: RO7, 12: FM1, 13: WKFARM, 14: AN1, 15: NF1, 16: NFBN1, 17: NFBN21, 18: NFBN41, 19: NFDAYS, 20: NFHOURS, 21: IN11S1, 22: IN13S1, 23: IN11S2, 24: IN13S2, 25: IN11S3, 26: IN13S3, 27: IN11S4, 28: IN13S4, 29: IN11S5, 30: IN13S5, 31: IN11S6, 32: IN13S6, 33: IN11S7, 34: IN13S7, 35: IN11S8, 36: IN13S8, 37: ED2, 38: ED3, 39: ED4, 40: ED6, 41: EDUC7, 42: EDUNDER1, 43: MM7Y, 44: MM12Y, 45: CS3Y, 46: SM3, 47: SM4, 48: SM5, 49: SM7, 50: SM11, 51: SM12, 52: SM18, 53: SM20, 54: SM21, 55: SM22, 56: MB3, 57: MB4, 58: MB5, 59: MB6, 60: MB7, 61: MB8, 62: MB9, 63: MB10, 64: MB11, 65: MB12, 66: MB13, 67: MB14, 68: MB15, 69: MB16, 70: MB17, 71: MB18, 72: MB19, 73: MB25, 74: MB27, 75: MB28, 76: MB29, 77: AD3, 78: AD4, 79: AD5, 80: AD6, 81: AD7, 82: AD8, 83: AD9, 84: EW3Y, 85: URBAN2011, 86: URBA

In [7]:
household = pd.read_csv("ihds_household_data.tsv",sep="\t")

/var/folders/rt/g1_x8zrs5fd4xd6r10k55jrm0000gn/T/ipykernel_5998/1762404375.py:1: DtypeWarning: Columns (0: HS3D, 1: HS3M, 2: HS3Y, 3: HS3DATE, 4: HS4A, 5: HS4B, 6: HS4C, 7: ID11, 8: ID13, 9: GROUPS, 10: ID14, 11: ID15, 12: ID18A, 13: ID18C, 14: MG1, 15: AN2A, 16: AN2B, 17: AN2C, 18: AN2D, 19: AN2E, 20: AN3A1, 21: AN3A2, 22: AN3B1, 23: AN3B2, 24: AN3B3, 25: NFBN1, 26: IN1, 27: IN2, 28: IN3A, 29: IN3B, 30: IN4A, 31: IN4B, 32: IN5, 33: IN6, 34: IN7, 35: IN14, 36: IN15A1, 37: IN15A2, 38: IN15B1, 39: IN15B2, 40: IN15C1, 41: IN15C2, 42: IN15D1, 43: IN15D2, 44: IN15E1, 45: IN15F1, 46: IN15G1, 47: IN16, 48: IN17, 49: RC1, 50: RC1A, 51: RC1B1, 52: RC1B2, 53: RC1B3, 54: RC1B4, 55: RC1C, 56: RC1D, 57: RC3A, 58: RC3B, 59: RC3C, 60: RC4, 61: MM5, 62: MM10, 63: CO1A, 64: CO1B, 65: CO1D, 66: CO2A, 67: CO2B, 68: CO2D, 69: CO3A, 70: CO3B, 71: CO3D, 72: CO4A, 73: CO4D, 74: CO5A, 75: CO5D, 76: CO5E, 77: CO6C, 78: CO7C, 79: CO7X, 80: CO8C, 81: CO8X, 82: CO9A, 83: CO9B, 84: CO9C, 85: CO10C, 86: CO10X, 87: 

In [8]:
print("Individual:", individual.shape)
print("Household:", household.shape)

Individual: (204569, 337)
Household: (42152, 758)


In [9]:
### TARGET veriable from Individual data set 
# WKANY5 → Employment

# SENSITIVE ATTRIBUTES
#RO3   → Sex
#ID13  → Caste
#ID11  → Religion

#FEATURES
#RO5       → Age
#ED6       → Education
#URBAN2011 → Rural/Urban

In [10]:
important = [
    "RO3", "RO5", "ED6", "EDUC7",
    "ID11", "ID13", "GROUPS",
    "URBAN2011", "WKANY5"
]

In [11]:
individual[important].head(10)

,RO3,RO5,ED6,EDUC7,ID11,ID13,GROUPS,URBAN2011,WKANY5
0,1,57,0,0,2,3,6,0,4
1,2,49,0,0,2,3,6,0,2
2,1,19,9,8,2,3,6,0,4
3,2,14,5,5,2,3,6,0,0
4,1,29,9,8,2,3,6,0,4
5,2,26,8,8,2,3,6,0,0
6,1,7,1,3,2,3,6,0,0
7,2,4,0,0,2,3,6,0,0
8,1,2,0,0,2,3,6,0,0
9,1,76,12,12,2,,6,0,0


In [ ]:
#RO3 variable is Sex in your IHDS-II data:
# 1 = Male
# 2 = Female

In [12]:
print(individual["RO3"].unique())

[1 2 '2' '1' ' ']


In [ ]:
# cleaning RO3 data 

In [13]:
individual["RO3"] = pd.to_numeric(
    individual["RO3"].astype(str).str.strip(),
    errors="coerce"
)

In [14]:
individual["RO3"].isna().sum()

np.int64(1)

In [ ]:
#only 1 number is Null so we will delate that row 

In [15]:
individual = individual.dropna(subset=["RO3"]).copy()

In [18]:
individual["RO3"].unique()

array([1., 2.])

In [ ]:
#convert the remaining values to integers

In [16]:
individual["RO3"] = individual["RO3"].astype(int)

In [ ]:
# RO5 is the age of the individual/person in the IHDS-II dataset

In [17]:
individual["RO5"].unique()

array([57, 49, 19, 14, 29, 26, 7, 4, 2, 76, 42, 40, 20, 13, 37, 33, 8, 6,
       31, 3, 65, 45, 43, 23, 17, 12, 47, 50, 38, 27, 25, 1, 21, 18, 16,
       72, 39, 24, 52, 15, 0, 48, 30, 22, 67, 28, 11, 9, 10, 60, 56, 35,
       36, 59, 77, 62, 41, 51, 66, 81, 71, 61, 32, 53, 34, 5, 44, 79, 54,
       46, 55, 93, 64, 90, 58, 87, 68, 70, 75, 63, 82, 99, 69, 85, 92, 73,
       97, 86, 80, 78, 74, 83, 84, 95, 88, 98, 94, 89, 91, 96, '35', '20',
       '15', '42', '19', '4', '3', '34', '28', '10', '5', '50', '45',
       '39', '16', '59', '48', '26', '24', '1', '22', '6', '57', '52',
       '49', '72', '46', '21', '32', '29', '7', '13', '66', '30', '12',
       '9', '25', '8', '2', '61', '11', '37', '18', '51', '43', '64',
       '54', '27', '73', '67', '31', '0', '44', '23', '40', '62', '47',
       '14', '41', '55', '56', '53', '38', '17', '63', '75', '82', '58',
       '76', '60', '33', '80', '91', '71', '68', '81', '36', '70', '65',
       '77', '84', '90', '69', '92', '78', '86', '79', 

In [ ]:
#cleaning RO5 column

In [18]:
individual["RO5"] = pd.to_numeric(
    individual["RO5"].astype(str).str.strip(),
    errors="coerce"
)

In [ ]:
#finding null values

In [19]:
individual["RO5"].isna().sum()

np.int64(3)

In [ ]:
#removing null vales

In [20]:
individual =individual.dropna(subset=["RO5"]).copy()

In [ ]:
#Findinf Minimum and maximum age 

In [21]:
print("Minimum age:", individual["RO5"].min())
print("Maximum age:", individual["RO5"].max())

Minimum age: 0.0
Maximum age: 99.0


In [22]:
individual["RO5"] = individual["RO5"].astype(int)

In [ ]:
# EDUC7 is  a grouped education variable
#EDUC7 value	Meaning
# 0	None
# 3	1–4 years
# 5	Primary
# 8	6–9 years
# 10	Secondary (and 11th)
# 12	Higher secondary (including 13–14)
# 15	Graduate
# 16	Some post-graduate

In [23]:
individual["EDUC7"].unique()

array(['0', '8', '5', '3', '12', '15', '16', '10', ' ', 3, 0, 8, 15, 12,
       10, 5, 16], dtype=object)

In [24]:
individual["EDUC7"] = pd.to_numeric(
    individual["EDUC7"].astype(str).str.strip(),
    errors="coerce"
)

In [25]:
individual["EDUC7"].isna().sum()

np.int64(232)

In [26]:
#232 missing values in EDUC7 out of roughly 204,000 records is only about 0.11%, so dropping them

In [27]:
individual =individual.dropna(subset=["EDUC7"]).copy()

In [28]:
print(individual["EDUC7"].unique())

[ 0.  8.  5.  3. 12. 15. 16. 10.]


In [29]:
individual["EDUC7"] = individual["EDUC7"].astype(int)

In [30]:
# ID11 is Religion column
#ID11	Religion
#1	Hindu
#2	Muslim
#3	Christian
#4	Sikh
#5	Buddhist
#6	Jain
#7	Tribal
#8	Others
#9	None

In [31]:
individual["ID11"].unique()

array([2, 5, 1, 3, 6, 4, 7, 8, '2', '1', '5', '3', '7', '9', '8', ' ', 9,
       '6'], dtype=object)

In [32]:
individual["ID11"] = pd.to_numeric(
    individual["ID11"].astype(str).str.strip(),
    errors="coerce"
)

In [33]:
individual["ID11"].isna().sum()

np.int64(1)

In [34]:
individual =individual.dropna(subset=["ID11"]).copy()

In [35]:
individual["ID11"] = individual["ID11"].astype(int)

In [36]:
individual["ID11"].value_counts(dropna=False)

ID11
1    163718
2     27750
3      5251
4      4777
5      1204
7       910
6       486
8       185
9        51
Name: count, dtype: int64

In [37]:
# ID13 represents caste/social category in your IHDS-II data.
#ID13	Category
#1	Brahmin
#2	Forward/General (except Brahmin)
#3	Other Backward Castes (OBC)
#4	Scheduled Castes (SC)
#5	Scheduled Tribes (ST)
#6	Others

In [38]:
individual["ID13"].unique()

array(['3', ' ', '2', '5', '6', '4', '1', 2, 3, 5, 4, 1, 6], dtype=object)

In [39]:
individual["ID13"] = pd.to_numeric(
    individual["ID13"].astype(str).str.strip(),
    errors="coerce"
)

In [40]:
individual["ID13"].isna().sum()

np.int64(451)

In [41]:
# 451 value are missing only .02 so we will delate it 

In [42]:
individual =individual.dropna(subset=["ID13"]).copy()

In [43]:
individual["ID13"] = individual["ID13"].astype(int)

In [44]:
individual["ID13"].value_counts(dropna=False)

ID13
3    83821
2    46816
4    43089
5    17354
1    10248
6     2553
Name: count, dtype: int64

In [45]:
# GROUPS represents a combined social-group classification in IHDS-II, 
#bringing caste and religion together into broader categories.
#GROUPS	Social group
#1	Brahmin
#2	Forward Caste
#3	OBC
#4	Dalit
#5	Adivasi
#6	Muslim
#7	Christian, Sikh, Jain

In [46]:
individual["GROUPS"].unique()

array(['6', '5', '2', '4', '1', 6, 5, 2, 4, 1, 3, 7, '3', '7'],
      dtype=object)

In [47]:
individual["GROUPS"] = pd.to_numeric(
    individual["GROUPS"].astype(str).str.strip(),
    errors="coerce"
)

In [48]:
individual["GROUPS"].isna().sum()

np.int64(0)

In [49]:
individual["GROUPS"] = individual["GROUPS"].astype(int)

In [50]:
individual["GROUPS"].value_counts(dropna=False)

GROUPS
3    68191
4    43089
2    32764
6    26962
5    17354
1    10174
7     5347
Name: count, dtype: int64

In [51]:
#URBAN2011 tells you whether the person's household was in a rural or urban area, 
#based on the 2011 Census classification.
#URBAN2011 = 0 → Rural
#URBAN2011 = 1 → Urban


In [52]:
individual["URBAN2011"].unique()

array([0, 1, '1', '0'], dtype=object)

In [53]:
individual["URBAN2011"] = pd.to_numeric(
    individual["URBAN2011"].astype(str).str.strip(),
    errors="coerce"
)

In [54]:
individual["URBAN2011"].isna().sum()

np.int64(0)

In [55]:
individual["URBAN2011"] = individual["URBAN2011"].astype(int)

In [56]:
individual["URBAN2011"].value_counts()

URBAN2011
0    134778
1     69103
Name: count, dtype: int64

In [57]:
#WKANY5 represents work participation / employment intensity in IHDS-II
# WKANY5	Meaning
#0	No work
#1	Worked, but hours are missing
#2	Worked less than 240 hours/year
#3	Part-time work
#4	Full-time/year work

In [58]:
individual["WKANY5"].unique()

array([4, 2, 0, 3, 1, '0', '4', '3', '2', '1'], dtype=object)

In [59]:
individual["WKANY5"] = pd.to_numeric(
    individual["WKANY5"].astype(str).str.strip(),
    errors="coerce"
)

In [60]:
individual["WKANY5"].isna().sum()

np.int64(0)

In [61]:
individual["WKANY5"] = individual["WKANY5"].astype(int)

In [62]:
individual["WKANY5"].value_counts()

WKANY5
0    111365
3     46971
4     31239
2     12228
1      2078
Name: count, dtype: int64

In [63]:
important = [
    "RO3", "RO5", "EDUC7",
    "ID11", "ID13", "GROUPS",
    "URBAN2011", "WKANY5"
]

individual[important].isna().sum()

RO3          0
RO5          0
EDUC7        0
ID11         0
ID13         0
GROUPS       0
URBAN2011    0
WKANY5       0
dtype: int64

In [64]:
individual.shape

(203881, 337)

In [65]:
model_data = individual[important].copy()

model_data.head()

,RO3,RO5,EDUC7,ID11,ID13,GROUPS,URBAN2011,WKANY5
0,1,57,0,2,3,6,0,4
1,2,49,0,2,3,6,0,2
2,1,19,8,2,3,6,0,4
3,2,14,5,2,3,6,0,0
4,1,29,8,2,3,6,0,4


In [ ]:
#we are taking only working age from RO5 column which is age vaeriable 


In [66]:
data = individual[
    (individual["RO5"] >= 18) &
    (individual["RO5"] <= 64)
].copy()

print("Original:", individual.shape)
print("Working-age:", data.shape)

Original: (203881, 337)
Working-age: (120842, 337)


In [ ]:
#just taking 7 varibale column data for our project 

In [67]:
columns = [
    "RO3",
    "RO5",
    "EDUC7",
    "ID11",
    "ID13",
    "GROUPS",
    "URBAN2011",
    "WKANY5"
]

data = data[columns].copy()

data.head()

,RO3,RO5,EDUC7,ID11,ID13,GROUPS,URBAN2011,WKANY5
0,1,57,0,2,3,6,0,4
1,2,49,0,2,3,6,0,2
2,1,19,8,2,3,6,0,4
4,1,29,8,2,3,6,0,4
5,2,26,8,2,3,6,0,0


In [ ]:
#WKANY5 is target variable 
#WKANY5 is  employed/unemployed variable. 
#In IHDS-II it represents categories of work participation:

#WKANY5	Meaning
#0	No work
#1	Work reported, hours missing
#2	Less than 240 hours
#3	Part-time
#4	Full-time/year

In [ ]:
#Problem Statment 
#Can a machine-learning model predict whether a working-age person has substantial 
#employment, and do its errors/outcomes differ by sex, caste and religion?

In [ ]:
#We can define substantial employment 
#as WKANY5 categories 3 or 4, versus categories 0 or 2. 
#Category 1 can be excluded because the work hours are missing.

In [68]:
data = data[data["WKANY5"] != 1].copy()

data["employed"] = data["WKANY5"].isin([3, 4]).astype(int)

In [69]:
data["employed"].value_counts()

employed
1    71261
0    48047
Name: count, dtype: int64

In [ ]:
#employed = 1  substantial employment
#employed = 0  no/low work participation

In [70]:
data[["RO5", "EDUC7", "RO3", "ID13", "ID11", "WKANY5", "employed"]].head(20)

,RO5,EDUC7,RO3,ID13,ID11,WKANY5,employed
0,57,0,1,3,2,4,1
1,49,0,2,3,2,2,0
2,19,8,1,3,2,4,1
4,29,8,1,3,2,4,1
5,26,8,2,3,2,0,0
25,45,10,1,3,2,4,1
26,43,0,2,3,2,3,1
27,23,10,2,3,2,0,0
28,20,12,1,3,2,0,0
32,57,0,1,2,2,4,1


In [71]:
data["employed"].value_counts(normalize=True) * 100

employed
1    59.728602
0    40.271398
Name: proportion, dtype: float64

In [ ]:
#59.7 percentage is substantial employment
#40.3 no/low work participation

In [ ]:
#Employment by Sex

In [72]:
sex_employment = data.groupby("RO3")["employed"].agg(
    count="count",
    employment_rate="mean"
)

sex_employment["employment_rate_percent"] = (
    sex_employment["employment_rate"] * 100
)

sex_employment

,count,employment_rate,employment_rate_percent
RO3,,,
1,58013,0.827349,82.734904
2,61295,0.379542,37.954156


In [ ]:
# 1 in RO3 mean - men which is 82.7 perc. empolyed
#0 in RO3 mean - female which is 37.9 perc. Empolyed 
#women in this sample have a substantially lower observed employment rate than men.

In [73]:
male_rate = data.loc[data["RO3"] == 1, "employed"].mean()
female_rate = data.loc[data["RO3"] == 2, "employed"].mean()

sex_gap = female_rate - male_rate

print("Male rate:", round(male_rate * 100, 2), "%")
print("Female rate:", round(female_rate * 100, 2), "%")
print("Female - Male gap:", round(sex_gap * 100, 2), "percentage points")

Male rate: 82.73 %
Female rate: 37.95 %
Female - Male gap: -44.78 percentage points


In [ ]:
#caste/social-group baseline 

In [74]:
caste_employment = data.groupby("ID13")["employed"].agg(
    count="count",
    employment_rate="mean"
)

caste_employment["employment_rate_percent"] = (
    caste_employment["employment_rate"] * 100
)

caste_employment

,count,employment_rate,employment_rate_percent
ID13,,,
1,6178,0.495792,49.579152
2,28334,0.535999,53.599915
3,48239,0.600075,60.007463
4,24767,0.636371,63.637098
5,10175,0.719214,71.921376
6,1615,0.609907,60.990712


In [ ]:
# ID13 represents caste/social category in your IHDS-II data.
#ID13	Category
#1	Brahmin   - 49.5 %
#2	Forward/General (except Brahmin)-- 53.6 %
#3	Other Backward Castes (OBC)  -- 60 %
#4	Scheduled Castes (SC) -- 63.6 %
#5	Scheduled Tribes (ST) -- 71.9 %
#6	Others -- 60.9 %

In [ ]:
#Social group:

#Lowest here: Brahmin 49.58%
#Highest here: Scheduled Tribe 71.92%
#Range: about 22.34 percentage points

In [ ]:
#finding empoyment rate in differnt  Regligon 

In [75]:
religion_employment = data.groupby("ID11")["employed"].agg(
    count="count",
    employment_rate="mean"
)

religion_employment["employment_rate_percent"] = (
    religion_employment["employment_rate"] * 100
)

religion_employment

,count,employment_rate,employment_rate_percent
ID11,,,
1,96441,0.614500,61.450006
2,14885,0.507424,50.742358
3,3263,0.560834,56.083359
4,2900,0.528276,52.827586
5,782,0.626598,62.659847
6,317,0.511041,51.104101
7,581,0.602410,60.240964
8,102,0.656863,65.686275
9,37,0.378378,37.837838


In [ ]:
#bringing caste and religion together into broader categories.
#GROUPS	Social group
#1	Brahmin  - 61.4%
#2	Forward Caste- 50.7 %
#3	OBC -- 52.0 %
#4	Dalit -- 52.8 %
#5	Adivasi -- 62.6 %
#6	Muslim -- 51.1%
#7	Christian -- 60.2 %
#8  Sikh -- 65.7%
#9  Jain -- 37.8 %

## Baseline Analysis Results

**Overall substantial employment:** 59.73%

**Sex**
- Male: 82.73%
- Female: 37.95%
- Female–Male gap: -44.78 percentage points

**Social Group**
Employment rates vary substantially across social groups.

**Religion**
Employment rates also vary across religious groups.

**machine-learning model**

let buit model with age , education and urban or rural column 
and target variable will be employed 
RO5       → Age
EDUC7     → Education
URBAN2011 → Rural/Urban

In [76]:
X = data[[
    "RO5",
    "EDUC7",
    "URBAN2011"
]].copy()

y = data["employed"].copy()

print("X shape:", X.shape)
print("y shape:", y.shape)

X.head()

X shape: (119308, 3)
y shape: (119308,)


,RO5,EDUC7,URBAN2011
0,57,0,0
1,49,0,0
2,19,8,0
4,29,8,0
5,26,8,0


In [77]:
X.isna().sum()

RO5          0
EDUC7        0
URBAN2011    0
dtype: int64

In [78]:
X.dtypes

RO5          int64
EDUC7        int64
URBAN2011    int64
dtype: object

In [79]:
print("Age:")
print(X["RO5"].value_counts().sort_index())

print("\nEducation:")
print(X["EDUC7"].value_counts().sort_index())

print("\nUrban/Rural:")
print(X["URBAN2011"].value_counts().sort_index())

Age:
RO5
18    3617
19    4401
20    4867
21    3433
22    4459
23    3170
24    3253
25    4530
26    3214
27    2816
28    3820
29    2032
30    4583
31    1766
32    3710
33    1898
34    1877
35    4410
36    2484
37    2173
38    2966
39    1592
40    4457
41    1322
42    3432
43    1716
44    1377
45    4398
46    1787
47    1990
48    2387
49    1193
50    3529
51    1088
52    2460
53    1129
54    1036
55    3199
56    1251
57    1252
58    1520
59     675
60    3377
61     714
62    1732
63     653
64     563
Name: count, dtype: int64

Education:
EDUC7
0     32638
3      8565
5      9425
8     28424
10    15668
12    13699
15     7291
16     3598
Name: count, dtype: int64

Urban/Rural:
URBAN2011
0    76247
1    43061
Name: count, dtype: int64


**Spliting Train and test data**


In [80]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

In [81]:
print("Training:")
print(y_train.value_counts(normalize=True) * 100)

print("\nTesting:")
print(y_test.value_counts(normalize=True) * 100)

Training:
employed
1    59.729061
0    40.270939
Name: proportion, dtype: float64

Testing:
employed
1    59.726762
0    40.273238
Name: proportion, dtype: float64


In [82]:
print("EDUC7:")
print(X_train["EDUC7"].value_counts().sort_index())

print("\nURBAN2011:")
print(X_train["URBAN2011"].value_counts().sort_index())

EDUC7:
EDUC7
0     26149
3      6851
5      7528
8     22697
10    12488
12    10984
15     5868
16     2881
Name: count, dtype: int64

URBAN2011:
URBAN2011
0    60949
1    34497
Name: count, dtype: int64


In [83]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler

numeric_features = ["RO5"]
categorical_features = ["EDUC7", "URBAN2011"]

preprocessor = ColumnTransformer(
    transformers=[
        ("num", StandardScaler(), numeric_features),
        ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_features)
    ]
)

Logistic regression model 

In [84]:
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression

model = Pipeline([
    ("preprocessor", preprocessor),
    ("classifier", LogisticRegression(max_iter=1000))
])

Training model

In [85]:
model.fit(X_train, y_train)

,"steps steps: list of tuplesList of (name of step, estimator) tuples that are to be chained insequential order. To be compatible with the scikit-learn API, all stepsmust define `fit`. All non-last steps must also define `transform`. See:ref:`Combining Estimators <combining_estimators>` for more details.","[('preprocessor', ...), ('classifier', ...)]"
,"transform_input transform_input: list of str, default=NoneThe names of the :term:`metadata` parameters that should be transformed by thepipeline before passing it to the step consuming it.This enables transforming some input arguments to ``fit`` (other than ``X``)to be transformed by the steps of the pipeline up to the step which requiresthem. Requirement is defined via :ref:`metadata routing <metadata_routing>`.For instance, this can be used to pass a validation set through the pipeline.You can only set this if metadata routing is enabled, which youcan enable using ``sklearn.set_config(enable_metadata_routing=True)``... versionadded:: 1.6",None
,"memory memory: str or object with the joblib.Memory interface, default=NoneUsed to cache the fitted transformers of the pipeline. The last stepwill never be cached, even if it is a transformer. By default, nocaching is performed. If a string is given, it is the path to thecaching directory. Enabling caching triggers a clone of the transformersbefore fitting. Therefore, the transformer instance given to thepipeline cannot be inspected directly. Use the attribute ``named_steps``or ``steps`` to inspect estimators within the pipeline. Caching thetransformers is advantageous when fitting is time consuming. See:ref:`sphx_glr_auto_examples_neighbors_plot_caching_nearest_neighbors.py`for an example on how to enable caching.",None
,"verbose verbose: bool, default=FalseIf True, the time elapsed while fitting each step will be printed as itis completed.",False
Name,Type,Value
"classes_ classes_: ndarray of shape (n_classes,)The classes labels. Only exist if the last step of the pipeline is aclassifier.","ndarray[int64](2,)","[0,1]"
"feature_names_in_ feature_names_in_: ndarray of shape (`n_features_in_`,)Names of features seen during :term:`fit`. Only defined if theunderlying estimator exposes such an attribute when fit... versionadded:: 1.0","ndarray[object](3,)","['RO5','EDUC7','URBAN2011']"
n_features_in_ n_features_in_: intNumber of features seen during :term:`fit`. Only defined if theunderlying first estimator in `steps` exposes such an attributewhen fit... versionadded:: 0.24,int,3
,"transformers transformers: list of tuplesList of (name, transformer, columns) tuples specifying thetransformer objects to be applied to subsets of the data.name : str Like in Pipeline and FeatureUnion, this allows the transformer and its parameters to be set using ``set_params`` and searched in grid search.transformer : {'drop', 'passthrough'} or estimator Estimator must support :term:`fit` and :term:`transform`. Special-cased strings 'drop' and 'passthrough' are accepted as well, to indicate to drop the columns or to pass them through untransformed, respectively.columns : str, array-like of str, int, array-like of int, array-like of bool, slice or callable Indexes the data on its second axis. Integers are interpreted as positional columns, while strings can reference DataFrame columns by name. A scalar string or int should be used where ``transformer`` expects X to be a 1d array-like (vector), otherwise a 2d array will be passed to the transformer. A callable is passed the input data `X` and can return any of the above. To select multiple columns by name or dtype, you can use :obj:`make_column_selector`.","[('num', ...), ('cat', ...)]"
,"remainder remainder: {'drop', 'passthrough'} or estimator, default='drop'By default, only the specified columns in `transformers` aretransformed and combined in the output, and the non-specifiedcolumns are dropped. (default of ``'drop'``).By specifying ``remainder='passthrough'``, all remaining columns thatwere not specified 

In [87]:
y_pred = model.predict(X_test)

In [88]:
from sklearn.metrics import accuracy_score, confusion_matrix

print("Accuracy:", round(accuracy_score(y_test, y_pred) * 100, 2), "%")

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy: 63.12 %

Confusion Matrix:
[[ 2845  6765]
 [ 2036 12216]]


In [89]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.58      0.30      0.39      9610
           1       0.64      0.86      0.74     14252

    accuracy                           0.63     23862
   macro avg       0.61      0.58      0.56     23862
weighted avg       0.62      0.63      0.60     23862



In [90]:
sex_test = data.loc[X_test.index, "RO3"]

print(sex_test.value_counts())

RO3
2    12273
1    11589
Name: count, dtype: int64


In [91]:
from fairlearn.metrics import (
    MetricFrame,
    selection_rate,
    true_positive_rate,
    false_positive_rate
)

sex_metrics = MetricFrame(
    metrics={
        "Selection Rate": selection_rate,
        "TPR": true_positive_rate,
        "FPR": false_positive_rate
    },
    y_true=y_test,
    y_pred=y_pred,
    sensitive_features=sex_test
)

sex_metrics.by_group


,Selection Rate,TPR,FPR
RO3,,,
1,0.787643,0.832723,0.574605
2,0.802819,0.906977,0.738466


In [92]:
from fairlearn.metrics import (
    demographic_parity_difference,
    equalized_odds_difference
)

dp_difference = demographic_parity_difference(
    y_test,
    y_pred,
    sensitive_features=sex_test
)

eo_difference = equalized_odds_difference(
    y_test,
    y_pred,
    sensitive_features=sex_test
)

print(
    "Demographic Parity Difference:",
    round(dp_difference, 4)
)

print(
    "Equalized Odds Difference:",
    round(eo_difference, 4)
)

Demographic Parity Difference: 0.0152
Equalized Odds Difference: 0.1639


## Sex-Based Fairness Audit

The classifier produced similar positive prediction rates across sex groups:

- Male selection rate: 78.76%
- Female selection rate: 80.28%
- Demographic parity difference: 0.0152

However, error rates differed substantially:

- Male TPR: 83.27%
- Female TPR: 90.70%
- Male FPR: 57.46%
- Female FPR: 73.85%
- Equalized odds difference: 0.1639

Although demographic parity suggests relatively similar selection rates,
equalized odds reveals a substantial difference in model error behavior.
In particular, the false-positive rate is considerably higher for women.

These results should not by themselves be interpreted as proof of
discrimination. They demonstrate group-level disparities in classifier
behavior that require further investigation.

**Get caste/social group for the test set**

In [93]:
caste_test = data.loc[X_test.index, "ID13"]

print(caste_test.value_counts().sort_index())

ID13
1    1213
2    5634
3    9610
4    5021
5    2066
6     318
Name: count, dtype: int64


Calculate fairness metrics by caste/social group

In [94]:
caste_metrics = MetricFrame(
    metrics={
        "Selection Rate": selection_rate,
        "TPR": true_positive_rate,
        "FPR": false_positive_rate
    },
    y_true=y_test,
    y_pred=y_pred,
    sensitive_features=caste_test
)

caste_metrics.by_group

,Selection Rate,TPR,FPR
ID13,,,
1,0.751855,0.824013,0.679339
2,0.764821,0.830658,0.686943
3,0.791467,0.848744,0.706808
4,0.809401,0.865873,0.710929
5,0.888190,0.942373,0.752961
6,0.801887,0.834197,0.752000


TPR

The model correctly recognizes actually-employed people at:

Brahmin: 82.40%
Forward/General: 83.07%
OBC: 84.87%
SC: 86.59%
ST: 94.24%
Others: 83.42%

The maximum gap is about 11.84 percentage points.

FPR


Brahmin: 67.93%
Forward/General: 68.69%
OBC: 70.68%
SC: 71.09%
ST: 75.30%
Others: 75.20%

In [95]:
caste_dp = demographic_parity_difference(
    y_test,
    y_pred,
    sensitive_features=caste_test
)

caste_eo = equalized_odds_difference(
    y_test,
    y_pred,
    sensitive_features=caste_test
)

print("Caste DP Difference:", round(caste_dp, 4))
print("Caste EO Difference:", round(caste_eo, 4))

Caste DP Difference: 0.1363
Caste EO Difference: 0.1184


Religion fairness

In [96]:
religion_test = data.loc[X_test.index, "ID11"]

print(religion_test.value_counts().sort_index())

ID11
1    19275
2     2963
3      676
4      589
5      160
6       54
7      120
8       17
9        8
Name: count, dtype: int64


In [97]:
religion_metrics = MetricFrame(
    metrics={
        "Selection Rate": selection_rate,
        "TPR": true_positive_rate,
        "FPR": false_positive_rate
    },
    y_true=y_test,
    y_pred=y_pred,
    sensitive_features=religion_test
)

religion_metrics.by_group

,Selection Rate,TPR,FPR
ID11,,,
1,0.803113,0.864150,0.705358
2,0.741141,0.802139,0.678937
3,0.795858,0.861619,0.709898
4,0.848896,0.880645,0.813620
5,0.687500,0.760417,0.578125
6,0.666667,0.640000,0.689655
7,0.825000,0.918033,0.728814
8,0.941176,1.000000,0.833333
9,0.750000,0.750000,0.750000


In [98]:
religion_dp = demographic_parity_difference(
    y_test,
    y_pred,
    sensitive_features=religion_test
)

religion_eo = equalized_odds_difference(
    y_test,
    y_pred,
    sensitive_features=religion_test
)

print("Religion DP Difference:", round(religion_dp, 4))
print("Religion EO Difference:", round(religion_eo, 4))

Religion DP Difference: 0.2745
Religion EO Difference: 0.36


At face value, religion shows the largest disparities of the three audits.

A DP difference of 0.2745 means the highest and lowest religion-group positive prediction rates differ by about 27.45 percentage points.

An EO difference of 0.36 means the largest disparity in TPR/FPR across religion groups is 36 percentage points.



In [99]:
religion_counts = religion_test.value_counts().sort_index()

religion_summary = religion_metrics.by_group.copy()
religion_summary["Test Count"] = religion_counts

religion_summary

,Selection Rate,TPR,FPR,Test Count
ID11,,,,
1,0.803113,0.864150,0.705358,19275
2,0.741141,0.802139,0.678937,2963
3,0.795858,0.861619,0.709898,676
4,0.848896,0.880645,0.813620,589
5,0.687500,0.760417,0.578125,160
6,0.666667,0.640000,0.689655,54
7,0.825000,0.918033,0.728814,120
8,0.941176,1.000000,0.833333,17
9,0.750000,0.750000,0.750000,8


In [100]:
religion_detail = pd.DataFrame({
    "Total": religion_test.value_counts().sort_index(),
    "Actual_1": y_test.groupby(religion_test).sum(),
    "Actual_0": y_test.groupby(religion_test).apply(lambda x: (x == 0).sum())
})

religion_detail

,Total,Actual_1,Actual_0
ID11,,,
1,19275,11866,7409
2,2963,1496,1467
3,676,383,293
4,589,310,279
5,160,96,64
6,54,25,29
7,120,61,59
8,17,11,6
9,8,4,4


Small-group sensitivity analysis: Religion fairness metrics are first calculated for all observed groups. Because max-difference fairness metrics can be highly sensitive to very small subgroups, a secondary analysis restricts the comparison to religion groups with at least 100 observations in the test set. This threshold is an exploratory stability criterion, not a universal statistical or fairness standard.

In [102]:
large_religion_groups = religion_counts[
    religion_counts >= 100
].index

mask = religion_test.isin(large_religion_groups)

religion_test_large = religion_test[mask]
y_test_large = y_test[mask]
y_pred_large = y_pred[mask]

In [103]:
religion_dp_large = demographic_parity_difference(
    y_test_large,
    y_pred_large,
    sensitive_features=religion_test_large
)

religion_eo_large = equalized_odds_difference(
    y_test_large,
    y_pred_large,
    sensitive_features=religion_test_large
)

print(
    "Religion DP Difference (N >= 100):",
    round(religion_dp_large, 4)
)

print(
    "Religion EO Difference (N >= 100):",
    round(religion_eo_large, 4)
)

Religion DP Difference (N >= 100): 0.1614
Religion EO Difference (N >= 100): 0.2355


## Model 1 Fairness Summary

The baseline logistic regression classifier was trained using age,
education and rural/urban residence, without directly including sex,
caste/social group or religion as predictors.

### Fairness results

| Attribute | DP Difference | EO Difference |
|---|---:|---:|
| Sex | 0.0152 | 0.1639 |
| Caste/Social Group | 0.1363 | 0.1184 |
| Religion (groups N >= 100) | 0.1614 | 0.2355 |

The results demonstrate that fairness conclusions depend on the metric
being examined.

For sex, positive prediction rates were relatively similar, while error
rates differed substantially.

For caste/social groups, disparities appeared in both selection rates
and error rates.

For religion, the initial disparity estimates were strongly affected by
very small groups. After restricting the exploratory comparison to
groups with at least 100 test observations, disparities remained but
were smaller.

These results demonstrate group-level disparities in classifier
behavior, but they do not by themselves establish discrimination or
causality.